baseURL = "https://miburi-silenthill.github.io/"
languageCode = "ja"
title = "みぶりのブログ"
theme = "PaperMod"
enableRobotsTXT = true

[permalinks]
  posts = "/posts/:slug/"

[pagination]
  pagerSize = 10

# 追加：検索と数式，コードハイライト，OG画像など
[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag      = "tags"

[params]
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowToc = true
  TocOpen = false
  images = ["images/og-default.png"]  # 用意できたら置く

  # 一覧にカバー画像を出すなら
  ShowCover = true
  cover = { linkFullImages = true, responsiveImages = true }

  # Fuse.js 検索の精度
  fuseOpts = { minMatchCharLength = 2, threshold = 0.3 }

  [params.homeInfoParams]
    Title = "私の数学ブログ"
    # “Example ページ”にリンクしたい場合は Markdown を使う
    Content = "ようこそ！ここに勉強法をまとめていきます．[Example ページを読む](/posts/example/)"

# Goldmark で生 HTML を許可（KaTeX など）
[markup.goldmark.renderer]
  unsafe = true

# Chroma（コードハイライト）
[markup.highlight]
  noClasses = false
  style = "github"
  lineNos = true

